server:
  port: 8085

spring:
  application:
    name: qr-ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ventry
    username: ventry
    password: ventry
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ticket
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: qr-ticket-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ventry.common.events"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
